services:
  # Frontend - Next.js Application
  - type: web
    name: ai-elearning-frontend
    env: node
    buildCommand: cd frontend && npm ci && NODE_OPTIONS="--max-old-space-size=4096" npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: ai-elearning-frontend
          property: host
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: ai-elearning-frontend
          property: host
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp-mail.outlook.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING
        value: "1"

  # Backend - FastAPI Application
  - type: web
    name: ai-elearning-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp-mail.outlook.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENTRY_DSN
        sync: false