#!/usr/bin/env node

/**
 * Sync environment variables from root .env.local to frontend/.env.local
 * This ensures both frontend and backend use the same environment variables
 */

const fs = require('fs');
const path = require('path');

const rootEnvPath = path.join(__dirname, '../.env.local');
const frontendEnvPath = path.join(__dirname, '../frontend/.env.local');

// Check if root .env.local exists
if (!fs.existsSync(rootEnvPath)) {
  console.error('Root .env.local file not found!');
  process.exit(1);
}

// Read root .env.local
const rootEnvContent = fs.readFileSync(rootEnvPath, 'utf8');

// Add a header to the frontend .env.local
const frontendEnvContent = `# AUTO-GENERATED FILE - DO NOT EDIT
# This file is automatically generated from the root .env.local
# To update environment variables, edit the root .env.local file
# Generated at: ${new Date().toISOString()}

${rootEnvContent}`;

// Write to frontend .env.local
fs.writeFileSync(frontendEnvPath, frontendEnvContent);

console.log('✅ Environment variables synced from root to frontend/.env.local');